name: Test tvOS build
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/tv-os-build-test.yml'
      - 'RNScreens.podspec'
      - 'package.json'
      - 'ios/**'
      - 'common/**'
      - 'FabricExample/**'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 60
    env:
      WORKING_DIRECTORY: FabricExample
      RNS_GAMMA_ENABLED: 0
    concurrency:
      group: ios-tv-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node.js (version from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/yarn.lock
      - name: Convert FabricExample for tvOS build
        run: ./scripts/convert-fabric-example-for-tv.sh
      - name: Install node dependencies in FabricExample
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
      - name: Install pods
        working-directory: ${{ env.WORKING_DIRECTORY }}/ios
        run: pod install
      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: detox build -c tvos.sim.debug
